src/main/java/com/example/backend/community/CommunityController.java
src/main/java/com/example/backend/community/domain/CommunityComment.java
src/main/java/com/example/backend/community/dto/CommunityCommentDto.java
src/main/java/com/example/backend/community/repository/CommunityCommentRepository.java
src/main/java/com/example/backend/community/service/CommunityBoardService.java
src/main/java/com/example/backend/community/service/CommunityCommentService.java

제목
---
잡담 게시판 댓글 등록 API 구현
잡담 게시글 등록 시 이미지 파일이 없는 경우 처리
작업내용
---
주의사항
---
User 연관관계 매핑 추가 예정
Controller Service 추후 리팩토링 예정

:sparkles:feat: 잡담게시판 댓글 등록 API

---

src/main/java/com/example/backend/community/domain/CommunityBoard.java
src/main/java/com/example/backend/community/domain/CommunityBoardImage.java
src/main/java/com/example/backend/community/domain/CommunityComment.java
src/main/java/com/example/backend/community/service/CommunityBoardService.java

제목
---
데이터베이스 communityBoard, communityComment, CommunityBoardImage 테이블명 단수형으로 변경
상세 잡담글 조회 시 댓글 중복조회 수정
상세 구현내용
---
작업사항
---
주의사항
---
테이블명 단수로 통일

🔨mod: 데이터베이스 테이블명 변경

---

build.gradle
src/main/java/com/example/backend/QueryDslConfiguration.java
src/main/java/com/example/backend/community/CommunityController.java
src/main/java/com/example/backend/community/domain/CommunityBoard.java
src/main/java/com/example/backend/community/domain/CommunityBoardImage.java
src/main/java/com/example/backend/community/domain/CommunityComment.java
src/main/java/com/example/backend/community/repository/CommunityBoardRepository.java
src/main/java/com/example/backend/community/repository/CustomCommunityRepository.java
src/main/java/com/example/backend/community/repository/CustomCommunityRepositoryImpl.java
src/main/java/com/example/backend/community/service/CommunityBoardService.java
src/main/java/com/example/backend/community/service/CommunityCommentService.java
src/main/java/com/example/backend/report/Report.java
src/main/java/com/example/backend/report/ReportRepository.java
src/main/java/com/example/backend/report/ReportService.java

제목
---
잡담게시글 ,댓글 신고 API
잡담게시글, 댓글 삭제 API
communityBoard, communityComment, communityBoardImage 테이블 status 필드 추가
상세 구현내용
---
queryDsl 추가: JPQL을 사용하여 쿼리문을 직접 작성하지 않아도, 자바로 작성한 코드를 쿼리문으로 반환하여 실행시켜주는 것. (쿼리문을 더 쉽게 짤 수 있게 도와줌) 
이거 환경설정을 추가했으니까 gradle 싱크 맞추고 아래 주의사항에 첨부한 링크 확인해서 compileJava까지 해주시면 됩니당~
작업사항
---
주의사항
---
1. **데이터베이스 변경사항 생김 -> 꼭 pull 받아오기 (풀 안받아오고 실행시키면 오빠 로컬에 있는 디비 코드랑 내 로컬 디비 코드가 달라져서 데이터베이스가 꼬여버림)**
2. 엔티티 생성 시 status 컬럼 추가 -> 삭제 관리
3. queryDsl 추가 
https://tecoble.techcourse.co.kr/post/2021-08-08-basic-querydsl/
이거 보고 compileJava 선택해서 QClass 만들어주면 됩니다~!

✨ feat, mod: 잡담게시판 신고, 삭제 API

---

src/main/java/com/example/backend/community/service/CommunityBoardService.java
src/main/java/com/example/backend/community/service/CommunityCommentService.java
src/main/java/com/example/backend/customHashtag/CustomHashtag.java
src/main/java/com/example/backend/customHashtag/CustomHashtagRepository.java
src/main/java/com/example/backend/video/VideoCommentService.java
src/main/java/com/example/backend/video/VideoController.java
src/main/java/com/example/backend/video/VideoService.java
src/main/java/com/example/backend/video/domain/Video.java
src/main/java/com/example/backend/video/domain/VideoComment.java
src/main/java/com/example/backend/video/dto/DetailVideoResponse.java
src/main/java/com/example/backend/video/dto/VideoCommentDto.java
src/main/java/com/example/backend/video/dto/VideoCommentsResponse.java
src/main/java/com/example/backend/video/repository/VideoCommentRepository.java

제목
---
VideoComment 엔티티 생성 및 매핑
영상 댓글 등록 API 구현
영상 댓글 등록 API 구현
상세 영상 조회 API 구현
상세 구현내용
---
VideoComment 엔티티 생성, Video와 매핑
Video와 Hashtag, CustomHashtag, Comment 양방향 매핑으로 변경
영상 댓글 등록 API, 상세 영상 정보 조회 API 구현
작업사항
---
주의사항
---
CustomHashtag 패키지 생성, 위치 이동

✨ feat: 영상 댓글 등록, 상세 영상 조회 API 구현

---

src/main/java/com/example/backend/community/dto/AllCommunityBoardsResponse.java
src/main/java/com/example/backend/community/dto/DetailCommunityBoardResponse.java
src/main/java/com/example/backend/community/repository/CommunityCommentRepository.java
src/main/java/com/example/backend/community/repository/CustomCommunityCommentRepository.java
src/main/java/com/example/backend/community/repository/CustomCommunityCommentRepositoryImpl.java
src/main/java/com/example/backend/community/repository/CustomCommunityRepositoryImpl.java
src/main/java/com/example/backend/community/service/CommunityBoardService.java
src/main/java/com/example/backend/community/service/CommunityCommentService.java
src/main/java/com/example/backend/video/VideoController.java
src/main/java/com/example/backend/video/VideoService.java
src/main/java/com/example/backend/video/dto/AllVideoResponse.java
src/main/java/com/example/backend/video/dto/AllVideoResponseWithPageCount.java
src/main/java/com/example/backend/video/repository/CustomVideoRepository.java
src/main/java/com/example/backend/video/repository/CustomVideoRepositoryImpl.java
src/main/java/com/example/backend/video/repository/VideoRepository.java

제목
---
전체 영상 조회 API, Best 영상 조회 API 구현 및 잡담게시글 조회 API 일부 오류 수정
상세 구현내용
---
전체 영상 조회 API - 해시태그 검색, 닉네임 검색, 페이징 구현
best 영상 조회 API - 좋아요수 기준 상위 4개 영상 조회 구현
잡담게시판 댓글 수 카운팅 수정, 전체 잡담게시글 조회 시 정렬 방식 수정
작업사항
---
주의사항
---
전체 영상 조회 API 검색 조건 확정 시 추가 구현 예정

✨ feat: 전체 영상 조회, BEST 영상 조회 API 구현

---

src/main/java/com/example/backend/community/CommunityController.java
src/main/java/com/example/backend/community/domain/CommunityBoard.java
src/main/java/com/example/backend/like/Like.java
src/main/java/com/example/backend/like/LikeRepository.java
src/main/java/com/example/backend/like/LikeService.java
src/main/java/com/example/backend/report/Report.java
src/main/java/com/example/backend/report/ReportRepository.java
src/main/java/com/example/backend/report/ReportService.java
src/main/java/com/example/backend/video/VideoCommentService.java
src/main/java/com/example/backend/video/VideoController.java
src/main/java/com/example/backend/video/VideoService.java
src/main/java/com/example/backend/video/domain/Video.java
src/main/java/com/example/backend/video/domain/VideoComment.java

제목
---
영상 신고/좋아요/삭제 API, 영상 댓글 신고/삭제 API
상세 구현내용
---
Report 엔티티 - Video, Video Comment 엔티티 매핑
Like 엔티티 - Video 엔티티 매핑
신고,삭제,좋아요 API 구현
작업사항
---
주의사항
---
좋아요 (likeService) 등록 방식 변경

✨ feat: 영상 신고,좋아요,삭제 API / 영상 댓글 신고,삭제 API 구현

---

src/main/java/com/example/backend/image/ImageController.java
src/main/java/com/example/backend/image/domain/ImageBoard.java
src/main/java/com/example/backend/image/repository/CustomImageRepositoryImpl.java
src/main/java/com/example/backend/image/service/ImageBoardService.java
src/main/java/com/example/backend/like/Like.java
src/main/java/com/example/backend/like/LikeRepository.java
src/main/java/com/example/backend/like/LikeService.java
src/main/java/com/example/backend/report/Report.java
src/main/java/com/example/backend/report/ReportRepository.java
src/main/java/com/example/backend/report/ReportService.java

[ADD] : 짤 게시판 좋아요 및 신고 연결

---

src/main/java/com/example/backend/image/ImageController.java
src/main/java/com/example/backend/image/dto/AllImageBoardsResponse.java
src/main/java/com/example/backend/image/dto/AllImageResponseWithPageCount.java
src/main/java/com/example/backend/image/dto/DetailImageBoardResponse.java
src/main/java/com/example/backend/image/dto/ImageBoardDto.java
src/main/java/com/example/backend/image/service/ImageBoardService.java

✨ [FEAT] : implement ImageBoard API(1)
-

✨ [FEAT] : implement ImageBoard API(1)

---

src/main/java/com/example/backend/like/Like.java

🐛 [FIX] : 깃헙 충돌해결
- [] 기능 추가
- [] 기능 수정
- [] 기타 설정
@ManyToOne 추가
-

🐛 [FIX] : 깃헙 충돌해결

---

src/main/java/com/example/backend/reservation/ReservationController.java
src/main/java/com/example/backend/reservation/ReservationService.java
src/main/java/com/example/backend/reservation/domain/ConfirmedReservation.java
src/main/java/com/example/backend/reservation/repository/CustomReservationRepository.java
src/main/java/com/example/backend/reservation/repository/CustomReservationRepositoryImpl.java
src/main/java/com/example/backend/reservation/repository/ReservationRepository.java

제목
---
영상 달리기 예약 - 예약 확정 기능 추가
작업내용
---
수정내용
---
1. 영상 예약 등록 시, 자동으로 **오늘날짜 이후** 의 전체 예약 내역들 중, **예약 기준을 달성한** 예약을 확정예약 데이터베이스에 추가
주의사항
---
아직 회원가입의 몇 퍼센트를 기준으로 할지 결정하지 않은 상태 -> 예약 확정 기준 = 2명으로 임시 설정

[ADD] 예약 확정 기능 추가

---

src/main/java/com/example/backend/playlist/PlaylistController.java
src/main/java/com/example/backend/playlist/PlaylistService.java
src/main/java/com/example/backend/playlist/domain/Playlist.java
src/main/java/com/example/backend/playlist/domain/PlaylistVideo.java
src/main/java/com/example/backend/playlist/dto/AddVideoDto.java
src/main/java/com/example/backend/playlist/dto/MyPlaylistResponse.java
src/main/java/com/example/backend/playlist/dto/NewEmptyPlaylistDto.java
src/main/java/com/example/backend/playlist/repository/CustomPlaylistVideoRepository.java
src/main/java/com/example/backend/playlist/repository/CustomPlaylistVideoRepositoryImpl.java
src/main/java/com/example/backend/playlist/repository/PlaylistRepository.java
src/main/java/com/example/backend/playlist/repository/PlaylistVideoRepository.java
src/main/java/com/example/backend/security/WebSecurityConfig.java

제목
---
플레이리스트 API (1) - 엔티티 생성, 플레이리스트 생성 API
작업내용
---
수정내용
---
1. 플레이리스트 엔티티 생성, 플레이리스트-비디오 M:N 매핑
2. 플레이리스트, 플레이리스트-비디오 레포지토리 생성
3. 새 빈 플레이리스트 생성 API 구현
4. 플레이리스트 영상 추가 API 구현
주의사항
---
closes #45

✨[FEAT/ADD] 플레이리스트 API (1)- 엔티티 생성, 플레이리스트 생성 API

---

src/main/java/com/example/backend/kakaoSocialLogin/service/OAuthService.java

제목
카카오톡 소셜 로그인 URL 변경
---
작업내용
---
수정내용
---
1. 수정 내용 작성
주의사항
---
주의사항 작성

카카오톡 소셜 로그인 URL 변경

---

src/main/java/com/example/backend/like/Like.java
src/main/java/com/example/backend/like/LikeRepository.java
src/main/java/com/example/backend/like/LikeService.java
src/main/java/com/example/backend/playlist/controller/PlaylistCommentController.java
src/main/java/com/example/backend/playlist/controller/PlaylistController.java
src/main/java/com/example/backend/playlist/domain/Playlist.java
src/main/java/com/example/backend/playlist/domain/PlaylistComment.java
src/main/java/com/example/backend/playlist/dto/TempPlaylistDto.java
src/main/java/com/example/backend/playlist/repository/CustomPlaylistRepository.java
src/main/java/com/example/backend/playlist/repository/CustomPlaylistRepositoryImpl.java
src/main/java/com/example/backend/playlist/service/PlaylistCommentService.java
src/main/java/com/example/backend/playlist/service/PlaylistService.java
src/main/java/com/example/backend/report/Report.java
src/main/java/com/example/backend/report/ReportRepository.java
src/main/java/com/example/backend/report/ReportService.java
src/main/java/com/example/backend/video/dto/TempVideoDto.java
src/main/java/com/example/backend/video/repository/CustomVideoRepository.java
src/main/java/com/example/backend/video/repository/CustomVideoRepositoryImpl.java
src/main/java/com/example/backend/video/service/VideoService.java

제목
---
플레이리스트 API 구현 완료
작업내용
---
수정내용
---
1. 플레이리스트 좋아요 등록/취소 API, 신고 API, 삭제 API 구현
2. 플레이리스트 댓글 신고, 삭제 API 구현
3. 전체 영상 조회 - 전체 페이지 수 수정
4. 전체 플레이리스트 조회 - 전체 페이지 수 수정
주의사항
---
fixes #55 
closes #46 , #47

[FEAT/FIX] 플레이리스트 구현 완료

---

src/main/java/com/example/backend/community/repository/CommunityBoardRepository.java
src/main/java/com/example/backend/community/repository/CustomCommunityRepository.java
src/main/java/com/example/backend/community/repository/CustomCommunityRepositoryImpl.java
src/main/java/com/example/backend/community/service/CommunityBoardService.java
src/main/java/com/example/backend/image/repository/CustomImageRepository.java
src/main/java/com/example/backend/image/repository/CustomImageRepositoryImpl.java
src/main/java/com/example/backend/main/MainController.java
src/main/java/com/example/backend/main/MainService.java
src/main/java/com/example/backend/main/dto/MainCommunityResponse.java
src/main/java/com/example/backend/main/dto/MainImageResponse.java
src/main/java/com/example/backend/main/dto/MainUserResponse.java
src/main/java/com/example/backend/main/dto/MainVideoResponse.java
src/main/java/com/example/backend/playlist/controller/PlaylistController.java
src/main/java/com/example/backend/playlist/repository/CustomPlaylistRepository.java
src/main/java/com/example/backend/playlist/repository/CustomPlaylistRepositoryImpl.java
src/main/java/com/example/backend/playlist/service/PlaylistService.java
src/main/java/com/example/backend/search/SearchController.java
src/main/java/com/example/backend/search/SearchService.java
src/main/java/com/example/backend/search/dto/SearchVideoResponse.java
src/main/java/com/example/backend/video/dto/AllVideoResponse.java
src/main/java/com/example/backend/video/repository/CustomVideoRepository.java
src/main/java/com/example/backend/video/repository/CustomVideoRepositoryImpl.java
src/main/java/com/example/backend/video/service/VideoService.java

제목
---
메인페이지/검색페이지 API
작업내용
---
수정내용
---
1. 메인페이지 API 구현
2. 검색페이지 API 구현
주의사항
---

[FEAT] 메인페이지/검색페이지 API

---

src/main/java/com/example/backend/playlist/controller/PlaylistController.java
src/main/java/com/example/backend/playlist/repository/CustomPlaylistRepository.java
src/main/java/com/example/backend/playlist/repository/CustomPlaylistRepositoryImpl.java
src/main/java/com/example/backend/playlist/service/PlaylistService.java
src/main/java/com/example/backend/reservation/dto/BestReservationResponse.java
src/main/java/com/example/backend/reservation/dto/NextRunResponse.java
src/main/java/com/example/backend/reservation/dto/TimetableResponse.java
src/main/java/com/example/backend/reservation/dto/VideoTitleSearchResponse.java
src/main/java/com/example/backend/video/dto/PlaylistVideoResponse.java

제목
---
resposne 수정
작업내용
---
수정내용
---
주의사항
---
주의사항 작성

[MOD] response 수정

---

src/main/java/com/example/backend/kakaoSocialLogin/OAuthController.java
src/main/java/com/example/backend/user/UserRepository.java
src/main/java/com/example/backend/user/UserService.java

제목
---
제목 작성
작업내용
---
수정내용
---
1. 수정 내용 작성
주의사항
---
주의사항 작성

[REMOVE] : KakaoId Entity

---

src/main/java/com/example/backend/kakaoSocialLogin/OAuthController.java
src/main/java/com/example/backend/user/domain/User.java

제목
---
제목 작성
작업내용
---
수정내용
---
1. 수정 내용 작성
주의사항
---
주의사항 작성

[MOD] : KAKAO SOCIAL LOGIN

---

src/main/java/com/example/backend/kakaoSocialLogin/OAuthController.java
src/main/java/com/example/backend/user/UserRepository.java
src/main/java/com/example/backend/user/UserService.java
src/main/java/com/example/backend/user/domain/User.java

제목
---
제목 작성
작업내용
---
수정내용
---
1. 수정 내용 작성
주의사항
---
주의사항 작성

[MOD] User Information

---

src/main/java/com/example/backend/image/ImageController.java
src/main/java/com/example/backend/image/dto/DetailImageBoardResponse.java
src/main/java/com/example/backend/image/dto/ImageBoardDto.java
src/main/java/com/example/backend/image/dto/TempImageDto.java
src/main/java/com/example/backend/image/repository/CustomImageRepository.java
src/main/java/com/example/backend/image/service/ImageBoardService.java

제목
짤 게시판 구현(1)
---
작업내용
---
수정내용
---
1. 수정 내용 작성
주의사항
---
주의사항 작성

[FEAT] : Implement ImageBoard

---

src/main/java/com/example/backend/image/dto/DetailImageBoardResponse.java
src/main/java/com/example/backend/image/repository/CustomImageRepository.java
src/main/java/com/example/backend/image/repository/CustomImageRepositoryImpl.java
src/main/java/com/example/backend/image/service/ImageBoardService.java

제목
상세짤조회 해시태그 추가
작업내용
---
수정내용
---
1. 수정 내용 작성
주의사항
---
주의사항 작성

[ADD] : 상세짤조회 해시태그 추가

---

src/main/java/com/example/backend/chat/ChatRoom.java
src/main/java/com/example/backend/image/dto/AllImageBoardsResponse.java

제목
전체 짤조회 imageUrl 추가
작업내용
---
수정내용
---
1. 수정 내용 작성
주의사항
---
주의사항 작성

전체 짤조회 imageUrl 추가

---

src/main/java/com/example/backend/chat/ChatController.java
src/main/java/com/example/backend/chat/ChatRoom.java
src/main/java/com/example/backend/chat/ChatRoomRepository.java
src/main/java/com/example/backend/chat/ChatService.java
src/main/java/com/example/backend/kakaoSocialLogin/JwtAuthenticationProvider.java
src/main/java/com/example/backend/kakaoSocialLogin/OAuthController.java
src/main/java/com/example/backend/kakaoSocialLogin/service/OAuthService.java
src/main/java/com/example/backend/running/RunningController.java
src/main/java/com/example/backend/user/UserRepository.java
src/main/java/com/example/backend/user/UserService.java
src/main/java/com/example/backend/user/domain/User.java

제목
카카오톡 소셜 로그인 수정
작업내용
---
- [x ] 기능 수정
수정내용
---
1. 수정 내용 작성
주의사항
---
주의사항 작성

카카오톡 소셜 로그인 수정

---

src/main/java/com/example/backend/reservation/ReservationController.java
src/main/java/com/example/backend/reservation/ReservationService.java
src/main/java/com/example/backend/reservation/dto/DetailReservationResponse.java
src/main/java/com/example/backend/reservation/repository/ReservationRepository.java

제목
---
제목 작성
작업내용
---
수정내용
---
1. 수정 내용 작성
주의사항
---
주의사항 작성

✨feat: 상세 예약 조회 API

---

src/main/java/com/example/backend/chat/WebSocketConfig.java
src/main/java/com/example/backend/user/UserService.java

제목
웹 소켓 핸들러 수정
작업내용
---
수정내용
---
주의사항
---
주의사항 작성

[MOD] : WebsocketHander

---

src/main/java/com/example/backend/running/RunningController.java

제목
실시간 달리기 방 영상 제목 제외
작업내용
---
수정내용
---
실시간 달리기 방 영상 제목 제외
주의사항
---
주의사항 작성

[MOD] : 실시간 달리기 방 영상 제목 제외

---

src/main/java/com/example/backend/chat/WebSocketConfig.java
src/main/java/com/example/backend/image/ImageController.java

제목
SocketJs Code
작업내용
---
수정내용
---
SocketJs Code
주의사항
---
주의사항 작성

[ADD] : SocketJs Code

---

src/main/java/com/example/backend/main/dto/MainUserResponse.java
src/main/java/com/example/backend/security/WebMvcConfig.java

제목
WebMvcConfig & main/user API
작업내용
---
수정내용
---
WebMvcConfig & main/user API
주의사항
---
주의사항 작성

[MOD] : WebMvcConfig & main/user API

---

src/main/java/com/example/backend/main/MainController.java

제목
[MOD] : UserInfo
작업내용
---
수정내용
[MOD] : UserInfo
주의사항
---
주의사항 작성

[MOD] : UserInfo

---

src/main/java/com/example/backend/chat/StompChatController.java

제목
채팅 API 테스트 변경
작업내용
---
수정내용
---
채팅 API 테스트 변경
주의사항
---
주의사항 작성

[MOD] : Chat API

---

src/main/java/com/example/backend/BackendApplication.java
src/main/java/com/example/backend/video/domain/Series.java
src/main/java/com/example/backend/video/repository/SeriesRepository.java
src/main/java/com/example/backend/video/service/ProgramCrawler.java

제목
---
프로그램명 (시리즈) 주기적 크롤링 기능 구현
작업내용
---
수정내용
---
1. 매주 일요일 0시 0분 0초에 방송사의 프로그램명을 크롤링, 데이터베이스에 저장되어 있지 않다면 저장하도록 구현
주의사항
---
1. 서버에 올라갔을 때 제대로 동작하는지는 나중에 확인할 수 있을 것 같습니다
2. 스케줄러 사용을 위해 `BackendApplication` 에 `@EnableScheduling` 어노테이션 추가

[프로그램 크롤링] 프로그램명 업데이트 기능 구현

---

src/main/java/com/example/backend/community/CommunityController.java
src/main/java/com/example/backend/image/ImageController.java
src/main/java/com/example/backend/playlist/controller/PlaylistCommentController.java
src/main/java/com/example/backend/playlist/controller/PlaylistController.java
src/main/java/com/example/backend/report/ReportService.java
src/main/java/com/example/backend/user/domain/User.java
src/main/java/com/example/backend/video/VideoController.java

제목
---
게시글 신고 기능 수정
작업내용
---
수정내용
---
1. 게시글을 신고할 경우, 신고 대상의 신고 횟수를 업데이트한다.
2. User 엔티티에 reportCount 횟수를 업데이트하는 메소드 추가
3. 이미지 / 잡담 / 플레이리스트 / 댓글 / 영상 게시글의 controller 에서 신고 요청을 보낼 경우, 신고 대상 User 객체를 함께 전달하도록 수정
주의사항
---
대상을 신고할 경우, Report 객체와 함께 신고 대상을 넘겨주어야 한다.

[게시글 신고] 신고 기능 수정

---

src/main/java/com/example/backend/customHashtag/CustomHashtagRepository.java
src/main/java/com/example/backend/image/ImageController.java
src/main/java/com/example/backend/image/domain/ImageBoard.java
src/main/java/com/example/backend/image/service/ImageBoardService.java
src/main/java/com/example/backend/oauth/service/OAuthService.java

제목
짤게시판 리팩토링 - 1st
작업내용
---
수정내용
- 일단 전반적으로 예전에 개발할 때, 너꺼를 다 따라했더니 고칠게 없어유,,,(대단)
- 짤 등록할 때, 짤 게시판은 1개의 파일만 올릴 수 있으므로 MultipartFile List를 MultipartFile로 수정
- 짤 삭제할 때, 해당 짤에 걸려있는 해시태그들 삭제 기능 추가
- 사용자가 아닌 사람이 짤을 삭제하려할 때 불가능하도록 기능 추가
주의사항
---
- 전체 짤 조회 API 리팩토링만 남았고 토요일까지 바뀐 API 문서 수정이랑 전체 짤 조회 API 리팩토링 진행하도록 하겠슴돠!

짤게시판 리팩토링 - 1st

---

src/main/java/com/example/backend/image/ImageController.java
src/main/java/com/example/backend/image/repository/CustomImageRepository.java
src/main/java/com/example/backend/image/repository/CustomImageRepositoryImpl.java
src/main/java/com/example/backend/image/service/ImageBoardService.java
src/main/java/com/example/backend/oauth/OAuthController.java

제목
짤게시판 전체조회 API 리팩토링
작업내용
---
수정내용
---
1. 카카오톡 소셜로그인 GET -> POST로 수정
2. 짤 게시판 전체조회 API 수정 (검색 기능이 없어서 그 부분 코드 지움!)
---
주의사항 작성

짤게시판 전체조회 API 리팩토링

---

src/main/java/com/example/backend/myPage/dto/MyDataDto.java

제목
---
제목 작성
작업내용
---
수정내용
---
1. 수정 내용 작성
주의사항
---
주의사항 작성

fix(MyDataDto): 필드 삭제

---

src/main/java/com/example/backend/oauth/OAuthController.java

제목
카카오톡 소셜로그인 파라미터 수정
작업내용
---
수정내용
---
accessCode 파라미터에 @RequestBody 어노테이션 추가 (raw로 받기위해)

카카오톡 소셜로그인 파라미터 수정

---

src/main/java/com/example/backend/oauth/OAuthController.java
src/main/java/com/example/backend/oauth/dto/OauthDto.java
src/main/java/com/example/backend/security/WebMvcConfig.java

제목
카카오톡 소셜로그인 수정 & CORS 설정
작업내용
---
수정내용
---
1. 카카오톡 소셜로그인 RequestBody -> RequestParm 으로 수정 및 GET으로 수정 (프론트 요청)
2. CORS 설정 (allowedCredential = true)
주의사항
---
- CORS 설정은 그냥 전 프로젝트에서 먹혔던 방법으로 코드 한 줄 덧붙였는데 될지는 모르겠어,, ㅠ

카카오톡 소셜로그인 수정 & CORS 설정

---

src/main/java/com/example/backend/security/WebSecurityConfig.java

제목
---
제목 작성
작업내용
---
수정내용
---
1. 수정 내용 작성
주의사항
---
주의사항 작성

fix(WebSecurityConfig): cors 설정 추가

---

src/main/java/com/example/backend/utils/JwtAuthenticationProvider.java

제목
---
토큰 유효시간 변경
작업내용
---
수정내용
---
- 토큰 유효기간 수정 (30분 -> 3시간)

토큰 유효시간 변경

---

src/main/java/com/example/backend/myPage/dto/UserEditInfoDto.java
src/main/java/com/example/backend/oauth/OAuthController.java
src/main/java/com/example/backend/user/domain/User.java
src/main/java/com/example/backend/user/repository/UserRepository.java
src/main/java/com/example/backend/user/service/UserService.java

제목
---
카카오톡 소셜로그인 회원가입 판별 컬럼 변경
작업내용
---
수정내용
---
- 카카오톡 소셜로그인 회원가입 판별 컬럼 변경

카카오톡 소셜로그인 회원가입 판별 컬럼 변경

---

src/main/java/com/example/backend/reservation/ReservationController.java

제목
---
제목 작성
작업내용
---
수정내용
---
1. 수정 내용 작성
주의사항
---
주의사항 작성

fix(ReservationController): 검색 파라미터 수정

---

src/main/java/com/example/backend/search/SearchService.java

제목
---
제목 작성
작업내용
---
수정내용
---
1. 수정 내용 작성
주의사항
---
주의사항 작성

🐛fix(SearchService): 충돌 해결 오류 수정

---

src/main/java/com/example/backend/playlist/controller/PlaylistController.java
src/main/java/com/example/backend/playlist/repository/CustomPlaylistRepository.java
src/main/java/com/example/backend/playlist/repository/CustomPlaylistRepositoryImpl.java
src/main/java/com/example/backend/playlist/service/PlaylistService.java
src/main/java/com/example/backend/video/VideoController.java
src/main/java/com/example/backend/video/repository/CustomVideoRepository.java
src/main/java/com/example/backend/video/repository/CustomVideoRepositoryImpl.java
src/main/java/com/example/backend/video/service/VideoService.java

전체 조회 시, 검색문이 없이 조회가 이루어진다.
제목
---
제목 작성
작업내용
---
수정내용
---
1. 수정 내용 작성
주의사항
---
주의사항 작성

🐛fix(Controller): 영상, 플레이리스트 조회 오류 수정

---

src/main/java/com/example/backend/security/WebSecurityConfig.java
src/main/java/com/example/backend/video/service/VideoService.java

제목
---
제목 작성
작업내용
---
수정내용
---
1. 수정 내용 작성
주의사항
---
주의사항 작성

[FIX] 영상 URL 검증 시 삭제된 영상 추가 허용

---

src/main/java/com/example/backend/myPage/MyPageService.java
src/main/java/com/example/backend/myPage/dto/UserInfoResponse.java
src/main/java/com/example/backend/video/repository/VideoRepository.java
src/main/java/com/example/backend/video/service/VideoService.java

제목
---
제목 작성
작업내용
---
수정내용
---
1. 수정 내용 작성
주의사항
---
주의사항 작성

fix: URL 검증 및 회원조회 오류 수정
